"""add mano field to players

Revision ID: 03992129c19c
Revises: 55f198506add
Create Date: 2026-07-19 14:26:54.624936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03992129c19c'
down_revision: Union[str, None] = '55f198506add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('mano', sa.String(length=20), server_default='Derecha', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'mano')
    # ### end Alembic commands ###