"""add player_id to notifications

Revision ID: 0eaa11c6b436
Revises: f21cea1ecfa6
Create Date: 2026-07-15 17:05:31.947148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eaa11c6b436'
down_revision: Union[str, None] = 'f21cea1ecfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('player_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'player_id')
    # ### end Alembic commands ###