"""add golpe_definitivo and nivel_amenaza to analyses

Revision ID: 196fe0bc4f27
Revises: c3473714ec9b
Create Date: 2026-06-26 08:17:57.296063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196fe0bc4f27'
down_revision: Union[str, None] = 'c3473714ec9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('golpe_definitivo', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('nivel_amenaza', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'nivel_amenaza')
    op.drop_column('analyses', 'golpe_definitivo')
    # ### end Alembic commands ###