"""add_player_id_to_tournaments

Revision ID: 1d19e414c1dc
Revises: 79c15a3bd2b1
Create Date: 2026-06-30 10:53:34.056613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d19e414c1dc'
down_revision: Union[str, None] = '79c15a3bd2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('player_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'player_id')
    # ### end Alembic commands ###