"""add rival torneo resultado ganado to matches

Revision ID: 5b1dcc84d45e
Revises: 196fe0bc4f27
Create Date: 2026-06-26 15:15:02.022931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1dcc84d45e'
down_revision: Union[str, None] = '196fe0bc4f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('rival_nombre', sa.String(length=150), nullable=True))
    op.add_column('matches', sa.Column('torneo', sa.String(length=150), nullable=True))
    op.add_column('matches', sa.Column('resultado', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('ganado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'ganado')
    op.drop_column('matches', 'resultado')
    op.drop_column('matches', 'torneo')
    op.drop_column('matches', 'rival_nombre')
    # ### end Alembic commands ###