"""add match_id to notifications

Revision ID: 7e5d30c40d8b
Revises: 0eaa11c6b436
Create Date: 2026-07-15 17:41:29.737588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5d30c40d8b'
down_revision: Union[str, None] = '0eaa11c6b436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE notifications ADD COLUMN IF NOT EXISTS match_id UUID")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notifications_match_id_fkey') THEN ALTER TABLE notifications ADD CONSTRAINT notifications_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id); END IF; END $$")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'match_id')
    # ### end Alembic commands ###