"""create initial tables

Revision ID: e6d2b70ee90b
Revises: 
Create Date: 2026-06-24 12:42:34.480105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d2b70ee90b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('INICIACION', 'QUINTA', 'CUARTA', 'TERCERA', 'SEGUNDA', 'PRIMERA', 'PRO', name='playercategory'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('derecha', sa.Integer(), nullable=True),
    sa.Column('reves', sa.Integer(), nullable=True),
    sa.Column('volea', sa.Integer(), nullable=True),
    sa.Column('bandeja', sa.Integer(), nullable=True),
    sa.Column('vibora', sa.Integer(), nullable=True),
    sa.Column('smash', sa.Integer(), nullable=True),
    sa.Column('lob', sa.Integer(), nullable=True),
    sa.Column('saque', sa.Integer(), nullable=True),
    sa.Column('bajada_pared', sa.Integer(), nullable=True),
    sa.Column('velocidad', sa.Integer(), nullable=True),
    sa.Column('resistencia', sa.Integer(), nullable=True),
    sa.Column('reflejos', sa.Integer(), nullable=True),
    sa.Column('tactica', sa.Integer(), nullable=True),
    sa.Column('presion', sa.Integer(), nullable=True),
    sa.Column('trabajo_en_pareja', sa.Integer(), nullable=True),
    sa.Column('torneos_jugados', sa.Integer(), nullable=True),
    sa.Column('victorias', sa.Integer(), nullable=True),
    sa.Column('puntos_ranking_fep', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('power_level', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('INICIACION', 'QUINTA', 'CUARTA', 'TERCERA', 'SEGUNDA', 'PRIMERA', 'PRO', name='playercategory'), nullable=False),
    sa.Column('ai_description', sa.Text(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('weaknesses', sa.Text(), nullable=False),
    sa.Column('improvement_plan', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player1_id', sa.UUID(), nullable=False),
    sa.Column('player2_id', sa.UUID(), nullable=False),
    sa.Column('scoring_method', sa.Enum('CON_VENTAJA', 'STAR_POINT', 'PUNTO_ORO', name='scoringmethod'), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('analyses')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###