"""add notifications table

Revision ID: f21cea1ecfa6
Revises: ffa8efd52f7f
Create Date: 2026-07-15 16:29:17.669355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21cea1ecfa6'
down_revision: Union[str, None] = 'ffa8efd52f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_partner_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_played_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_player1_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_tournaments_fep_points'), table_name='tournaments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tournaments_fep_points'), 'tournaments', ['fep_points'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_matches_player1_id'), 'matches', ['player1_id'], unique=False)
    op.create_index(op.f('ix_matches_played_at'), 'matches', ['played_at'], unique=False)
    op.create_index(op.f('ix_matches_partner_id'), 'matches', ['partner_id'], unique=False)
    # ### end Alembic commands ###